spring.application.name=restaurantService
server.port=8099

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27018/restaurant_db

foodDelivery.app.jwt.secret=foodDeliverySecretKeyWhichShouldBeVeryLongAndSecureanditneedstoberobustandwellmaintedwithalllfacilitiesandalsoneedtoconsideralsphabranvecenturykfdkaflkd

userService.baseUrl=http://localhost:8089

# Kafka Producer Configuration
spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.trusted.packages=*
logging.level.org.apache.kafka=INFO


# Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.userService.register-health-indicator=true
resilience4j.circuitbreaker.instances.userService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50

# Additional useful configurations
resilience4j.circuitbreaker.instances.userService.slow-call-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.slow-call-duration-threshold=5s

# Enable circuit breaker events
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.health.circuitbreakers.enabled=true
feign.circuitbreaker.enabled=true