spring.application.name=restaurantService
server.port=8099

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27018/restaurant_db

foodDelivery.app.jwt.secret=foodDeliverySecretKeyWhichShouldBeVeryLongAndSecureanditneedstoberobustandwellmaintedwithalllfacilitiesandalsoneedtoconsideralsphabranvecenturykfdkaflkd

userService.baseUrl=http://localhost:8089

# Kafka Producer Configuration
spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.trusted.packages=*
logging.level.org.apache.kafka=INFO