spring.application.name=notificationService
server.port=8083

# Service URLs
user.service.url=http://localhost:8089
restaurant.service.url=http://localhost:8089

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/notification-db

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:9092,localhost:9093
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Additional Kafka consumer configurations for order events
spring.kafka.consumer.properties.spring.json.type.mappings=userEvent:com.foodDelivery.notificationService.event.UserRegistrationEvent,orderEvent:com.foodDelivery.notificationService.event.OrderStatusEvent,passwordResetEvent:com.foodDelivery.notificationService.event.PasswordResetEvent,userRegistrationAdminEvent:com.foodDelivery.notificationService.event.UserRegistrationAdminEvent,userNotificationEvent:com.foodDelivery.notificationService.modal.UserNotificationEvent
# Logging
logging.level.com.foodDelivery.notificationService=DEBUG

# Service auth credentials
service.auth.username=asirijayawardena920@gmail.com
service.auth.password=asiri890@

# Enable scheduling
spring.task.scheduling.pool.size=5

#Mail Properties
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=f9ce3bb9a280e9
spring.mail.password=3ad9bde1264509

# Twilio Configuration
twilio.account.sid=AC47d0f30d5a7597657f50a20654825987
twilio.auth.token=56b178d120f6bad38b60632db0b991f7
twilio.phone.number=+12202348864

# Circuit breaker configuration
resilience4j.circuitbreaker.instances.emailService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.emailService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.emailService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.emailService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.emailService.waitDurationInOpenState=30000

resilience4j.circuitbreaker.instances.smsService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.smsService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.smsService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.smsService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.smsService.waitDurationInOpenState=30000




