spring.application.name=notificationService
server.port=8083

# Service URLs
user.service.url=http://localhost:8089
restaurant.service.url=http://localhost:8089

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/notification-db

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers.broker2=localhost:9093
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Additional Kafka consumer configurations for order events
spring.kafka.consumer.properties.spring.json.type.mappings=userEvent:com.foodDelivery.notificationService.event.UserRegistrationEvent,orderEvent:com.foodDelivery.notificationService.event.OrderStatusEvent,passwordResetEvent:com.foodDelivery.notificationService.event.PasswordResetEvent,userRegistrationAdminEvent:com.foodDelivery.notificationService.event.UserRegistrationAdminEvent,userNotificationEvent:com.foodDelivery.notificationService.modal.UserNotificationEvent
# Logging
logging.level.com.foodDelivery.notificationService=DEBUG

# Service auth credentials
service.auth.username=asirijayawardena920@gmail.com
service.auth.password=asiri890@

# Enable scheduling
spring.task.scheduling.pool.size=5

#Mail Properties
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d7798a006e9fd1
spring.mail.password=41a63f7ba6305c

# Twilio Configuration
twilio.account.sid=AC52ccd542b20ae8f2e5ff1827c72ee0e4
twilio.auth.token=f2671dd6785cdb0fbf7dd8b2d3d63eaf
twilio.phone.number=+19787332601

# Circuit breaker configuration
resilience4j.circuitbreaker.instances.emailService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.emailService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.emailService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.emailService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.emailService.waitDurationInOpenState=30000

resilience4j.circuitbreaker.instances.smsService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.smsService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.smsService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.smsService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.smsService.waitDurationInOpenState=30000




