spring.application.name=orderService
server.port=7083
restaurant.service.url=http://localhost:8089

foodDelivery.app.jwt.secret=foodDeliverySecretKeyWhichShouldBeVeryLongAndSecureanditneedstoberobustandwellmaintedwithalllfacilitiesandalsoneedtoconsideralsphabranvecenturykfdkaflkd
