spring.application.name=orderService
server.port=7083
restaurant.service.url=http://localhost:8089
user.service.url=http://localhost:8081

foodDelivery.app.jwt.secret=foodDeliverySecretKeyWhichShouldBeVeryLongAndSecureanditneedstoberobustandwellmaintedwithalllfacilitiesandalsoneedtoconsideralsphabranvecenturykfdkaflkd

#Kafka Producer Configuration
spring.kafka.bootstrap-servers=localhost:9032
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.trusted.packages=*
logging.level.org.apache.kafka=INFO